# Generated by Django 6.1.1 on 2026-09-20 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('fiatAmount', models.FloatField()),
                ('zecAmount', models.FloatField()),
                ('rate', models.FloatField()),
                ('fee', models.FloatField()),
                ('recipientCountry', models.CharField(max_length=10)),
                ('recipientBank', models.CharField(max_length=100)),
                ('recipientAccountNumber', models.CharField(max_length=50)),
                ('recipientAccountName', models.CharField(max_length=100)),
                ('paymentAddress', models.CharField(max_length=100)),
                ('status', models.CharField(default='AWAITING_ZEC', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='backend', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusHistory', to='orders.order')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
