# Generated by Django 6.1.1 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paymentAddress",
            field=models.CharField(max_length=1024),
        ),
    ]
